# References

CDC. (2025, December 4). Benefits of physical activity. Physical Activity Basics; Centers for

&nbsp;&nbsp;&nbsp;&nbsp; Disease Control and Prevention.

&nbsp;&nbsp;&nbsp;&nbsp; https://www.cdc.gov/physical-activity-basics/benefits/index.html


Climate Impact Partners. (2021, April 22). The carbon footprint of the internet.

&nbsp;&nbsp;&nbsp;&nbsp;www.climateimpact.com.

&nbsp;&nbsp;&nbsp;&nbsp;https://www.climateimpact.com/news-insights/insights/infographic-carbon-footprint-internet/


Climate Impact Partners. (2025, October 28). The Carbon Footprint of AI. Climateimpact.com.

&nbsp;&nbsp;&nbsp;&nbsp;https://www.climateimpact.com/news-insights/insights/carbon-footprint-of-ai/


Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality

&nbsp;&nbsp;&nbsp;&nbsp;Risk: a Meta-analytic Review. PLoS Medicine, 7(7).

&nbsp;&nbsp;&nbsp;&nbsp;https://doi.org/10.1371/journal.pmed.1000316


Hulscher, N. (2025, June 21). MIT Study Finds Artificial Intelligence Use Reprograms the

&nbsp;&nbsp;&nbsp;&nbsp;Brain, Leading to Cognitive Decline - Science, Public Health Policy

&nbsp;&nbsp;&nbsp;&nbsp;and the Law. Science, Public Health Policy and the Law; The Institute

&nbsp;&nbsp;&nbsp;&nbsp;for Pure and Applied Knowledge. 

&nbsp;&nbsp;&nbsp;&nbsp;https://publichealthpolicyjournal.com/mit-study-finds-artificial-inte

&nbsp;&nbsp;&nbsp;&nbsp;lligence-use-reprograms-the-brain-leading-to-cognitive-decline/


Jarvis, J. (2026, January 6). 10 Science-Backed Ways to Reduce Screen Time in 2026. Mind

&nbsp;&nbsp;&nbsp;&nbsp;Clarity Hub. https://mindclarityhub.com/ways-to-reduce-screen-time/


Kemp, S. (2024, January 31). What the world does online in 2024. DataReportal – Global

&nbsp;&nbsp;&nbsp;&nbsp;Digital Insights. 

&nbsp;&nbsp;&nbsp;&nbsp;https://datareportal.com/reports/digital-2024-deep-dive-what-we-do-online


Mark, G. (2023, February 8). Speaking of psychology: Why Our Attention Spans Are shrinking,

&nbsp;&nbsp;&nbsp;&nbsp;with Gloria Mark, PhD. American Psychological Association.

&nbsp;&nbsp;&nbsp;&nbsp;https://www.apa.org/news/podcasts/speaking-of-psychology/attention-spans


Morgan, L., & Doe, E. (2025, May 27). Internet Addiction and Mental Health (M. Blair, Ed.).

&nbsp;&nbsp;&nbsp;&nbsp;MentalHealth.com. https://www.mentalhealth.com/library/internet-addiction


Rossi, S., Fraccaro, V., & Manzotti, R. (2026). The brain side of human-AI interactions in

&nbsp;&nbsp;&nbsp;&nbsp;the long-term: the “3R principle.” Npj Artificial Intelligence, 2(1).

&nbsp;&nbsp;&nbsp;&nbsp;https://doi.org/10.1038/s44387-025-00063-1


Yilmaz, R., & Karaoglan Yilmaz, F. G. (2022). Problematic Internet use in Adults: The Role of

&nbsp;&nbsp;&nbsp;&nbsp;Happiness, Psychological Resilience, Dispositional Hope, and

&nbsp;&nbsp;&nbsp;&nbsp;Self-control and Self-management. Journal of Rational-Emotive &

&nbsp;&nbsp;&nbsp;&nbsp;Cognitive-Behavior Therapy. https://doi.org/10.1007/s10942-022-00482-y

